force-app/main/default/objects/Form_Session__c/Form_Session__c.object-meta.xml
<CustomObject>
    <label>Study Request Session</label>
    <nameField>
        <displayFormat>SRS-{00000}</displayFormat>
        <label>Study Request Session Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Request Sessions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Session__c/fields/Answers_JSON__c.field-meta.xml
<CustomField>
    <fullName>Answers_JSON__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Answers JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Form_Session__c/fields/Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Current_Step__c</fullName>
    <label>Current Step</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Form_Session__c/fields/Guest_Email__c.field-meta.xml
<CustomField>
    <fullName>Guest_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Guest Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Form_Session__c/fields/Session_Token__c.field-meta.xml
<CustomField>
    <fullName>Session_Token__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Session Token</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Form_Session__c/fields/Wizard_Type__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Wizard Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FormWizardStateModel.cls
public class FormWizardStateModel {

    public String primaryEmail;
    public String sessionName;
    public String sessionToken;
    public String sessionRecordId;
    public String formType;
    public String currentStep;
    public String answers;
    private Form_Session__c sessionRecord;

    public Map<String, Object> getAnswerMap() {
        if (String.isBlank(answers)) {
            return new Map<String, Object>();
        }
        return (Map<String, Object>) JSON.deserializeUntyped(answers);
    }

    // construct from study session record
    public FormWizardStateModel(Form_Session__c session) {
        this.sessionRecord      = session;
        this.sessionRecordId    = session.Id;
        this.sessionName        = session.Name;
        this.sessionToken       = session.Session_Token__c;
        this.formType           = session.Wizard_Type__c;
        this.primaryEmail       = session.Guest_Email__c;
        this.currentStep        = String.valueOf(session.Current_Step__c);
        this.answers            = session.Answers_JSON__c;
    }
}